### ISSUE TITLE
Feature request: natural sorting order of lessons in the course

### ISSUE THREAD

**Issue by vitaly-chibrikov** [mehanig/stepic_server_django#10]

**Comment by mehanig** [comment]
Users manually sort lessons and steps inside any instance. SubStep sorting not working. Steps sorting added with https://github.com/mehanig/stepic_server_django/commit/f3e4a83b080ee0a533c264c696287bf0b9a9a462 
Also checkbox for draggable added. First check the checkbox and then sort.
