### ISSUE TITLE
Feature request: natural sorting order of steps in lesson

### ISSUE THREAD

**Issue by vitaly-chibrikov** [mehanig/stepic_server_django#11]
![now it looks strange](https://cloud.githubusercontent.com/assets/339337/8354328/f5400640-1b4f-11e5-8a87-cd82cd7a60e1.jpg)

**Comment by mehanig** [comment]
Manual sorting added with https://github.com/mehanig/stepic_server_django/commit/f3e4a83b080ee0a533c264c696287bf0b9a9a462, before sorting check the checkbox "Make Draggable"
