### ISSUE TITLE
Sorting of lessons and steps

### ISSUE THREAD

**Issue by vitaly-chibrikov** [mehanig/stepic_server_django#13]
It does not work.
I try to move lesson by drag-and-drop. But instead of moving the browser opens it.
The same for steps.

Chrome 
Version 41.0.2272.89 (64-bit)
(work place)

**Comment by mehanig** [comment]
https://github.com/mehanig/stepic_server_django/issues/11 as descripted in this issue, did you tried checking "Make Draggable" checkbox before? this feature added by request of your college. you can now operate site with pen completely.
