### ISSUE TITLE
Step sorting

### ISSUE THREAD

**Issue by vyahhi** [mehanig/stepic_server_django#15]
`Step10from...` should go after `Step2from...` in the list. Because 10 is larger than 2 as a number.

P.S. Simple solution may be using 01, 02, 03 etc. instead of 1, 2, 3 etc.

**Comment by mehanig** [comment]
Order will be fixed next with next release. 

//If you have more than 9 SubSteps for 1 Video Step, you probably doing it wrong)

**Comment by mehanig** [comment]
https://github.com/mehanig/stepic_server_django/commit/c8519ec36af48145cb2640492d433d1543e45e21
Fixed with ordering by substep creation time. From now last substep will be always at the bottom.
